# Generated by Django 4.1 on 2022-08-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonatedMeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=30)),
                ('donated_by', models.CharField(max_length=70)),
                ('available', models.BooleanField()),
                ('location1', models.CharField(max_length=100)),
                ('location2', models.CharField(max_length=100)),
                ('location3', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=33)),
                ('phone', models.CharField(max_length=10)),
                ('med_photo', models.ImageField(upload_to='uploads/')),
                ('expiry_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone Number'),
        ),
    ]
