# Generated by Django 4.1 on 2022-08-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_donatedmeds_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetMeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=30)),
                ('received', models.BooleanField()),
                ('location1', models.CharField(max_length=100)),
                ('location2', models.CharField(max_length=100)),
                ('location3', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=33)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='donatedmeds',
            old_name='available',
            new_name='received',
        ),
    ]
